name: Formatting
on:
  # push:
  #   branches:
  #     - main
  #   tags: ['*']
  pull_request:
    types: [ opened, reopened, synchronize, labeled, unlabeled ]
  workflow_dispatch:
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v4
        with: 
          version: '2'
